name: Docker Tests & Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run tests with Docker Compose
      run: |
        docker compose --profile test build
        docker compose --profile test run test

    - name: Prepare coverage directory
      run: |
        mkdir -p ./reports/htmlcov
        mkdir -p ./coverage

    - name: Copy coverage reports from container
      run: |
        # Cerca anche container fermati (non solo in esecuzione)
        container_id=$(docker ps -a -q --filter "name=.*test.*" --latest)
        if [ -n "$container_id" ]; then
          echo "Copying coverage from container $container_id"
          docker cp $container_id:/app/htmlcov/. ./reports/htmlcov/ || echo "Failed to copy HTML coverage reports"
          docker cp $container_id:/app/.coverage ./coverage/.coverage || echo "Failed to copy .coverage file"
          docker cp $container_id:/app/coverage.xml ./coverage/coverage.xml || echo "Failed to copy coverage.xml file"
          # Rimuovi manualmente il container dopo la copia
          docker rm $container_id
        else
          echo "Test container not found!"
          exit 1
        fi

    - name: Upload coverage to Coveralls
      uses:  codecov/codecov-action@v3
      with:
        github-token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/coverage.xml
        format: cobertura


    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: reports/htmlcov/
        retention-days: 14
