name: Docker Tests & Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run tests with Docker Compose
      run: |
        docker compose --profile test build
        docker compose --profile test up --abort-on-container-exit

    - name: Copy coverage reports from container
      run: |
        container_id=$(docker ps -aq --filter name=test-container)
        docker cp $container_id:/app/coverage.xml ./coverage.xml
        docker cp $container_id:/app/htmlcov/. ./reports/htmlcov/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: reports/htmlcov/
        retention-days: 14